function cfg = get_project_config()

    configDir = fileparts(mfilename('fullpath'));
    cfg.projectRoot = fileparts(configDir);

    cfg.codeRoot = cfg.projectRoot;

  
    cfg.dataRoot = fullfile(cfg.projectRoot, 'data');
    cfg.outputRoot = fullfile(cfg.projectRoot, 'outputs');

    if ~exist(cfg.outputRoot, 'dir')
        mkdir(cfg.outputRoot);
    end
 
    activeFolders = { ...
        'config', ...
        'helper_functions', ...
        'preprocessing_qc', ...
        'feature_extraction', ...
        'feature_selection', ...
        'statistics', ...
        'classification', ...
        'classification/step75_modules', ...
        'permutation_testing', ...
        'manuscript_figures' ...
    };

    for i = 1:numel(activeFolders)
        p = fullfile(cfg.projectRoot, activeFolders{i});
        if exist(p, 'dir')
            addpath(p);
        end
    end
end
